{{- if .Values.envoyGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  {{- if .Values.envoyGateway.global.images.envoyProxy.image }}
  parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: custom-envoy-proxy
      namespace: {{ include "lbk-gateway.namespace" . }}
  {{- end }}
{{- end }}
