{{- if .Values.envoyGateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "lbk-gateway.namespace" . }}
  namespace: {{ include "lbk-gateway.namespace" . }}
spec:
  gatewayClassName: eg
  listeners:
  - name: web
    port: 80
    protocol: HTTP
{{- end }}
