{{- if .Values.metallb.enabled }}
{{- if eq .Values.metallb.mode "bgp" }}
{{- range .Values.metallb.bgpAdvertisements }}
---
apiVersion: metallb.io/v1beta2
kind: BGPAdvertisement
metadata:
  name: {{ .name }}
  namespace: {{ include "metal-gateway.namespace" $ }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "100"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  {{- with .ipAddressPools }}
  ipAddressPools:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .aggregationLength }}
  aggregationLength: {{ . }}
  {{- end }}
  {{- with .localPref }}
  localPref: {{ . }}
  {{- end }}
  {{- with .nodeSelectors }}
  nodeSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .communities }}
  communities:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
